apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dubbo-service.fullname" . }}
  labels:
    {{- include "dubbo-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dubbo-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dubbo-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: dubbo
              containerPort: {{ .Values.service.dubboPort }}
              protocol: TCP
          env:
            - name: NACOS_SERVER_ADDRESS
              value: {{ .Values.nacos.host | quote }}
            - name: NACOS_SERVER_PORT
              value: {{ .Values.nacos.port | quote }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
