// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greater.proto
// Protobuf Java Version: 4.33.2

package message;

@com.google.protobuf.Generated
public final class Greater extends com.google.protobuf.GeneratedFile {
  private Greater() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "Greater");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_message_GreeterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_message_GreeterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_message_GreeterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_message_GreeterReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rgreater.proto\022\030com.example.demo.messag" +
      "e\032\037google/protobuf/timestamp.proto\"\036\n\016Gr" +
      "eeterRequest\022\014\n\004name\030\001 \001(\t\"N\n\014GreeterRep" +
      "ly\022\017\n\007message\030\001 \001(\t\022-\n\ttimestamp\030\002 \001(\0132\032" +
      ".google.protobuf.Timestamp2d\n\007Greeter\022Y\n" +
      "\005greet\022(.com.example.demo.message.Greete" +
      "rRequest\032&.com.example.demo.message.Gree" +
      "terReplyB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_example_demo_message_GreeterRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_example_demo_message_GreeterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_message_GreeterRequest_descriptor,
        new String[] { "Name", });
    internal_static_com_example_demo_message_GreeterReply_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_com_example_demo_message_GreeterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_message_GreeterReply_descriptor,
        new String[] { "Message", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
