// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greater.proto
// Protobuf Java Version: 4.33.2

package message;

@com.google.protobuf.Generated
public interface GreeterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.message.GreeterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
